version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - ./.docker/.env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    env_file:
      - ./.docker/.env
    volumes:
      - ./ror:/ror
    ports:
      # Change the first number here to specify which port you want the Docker
      # container to run on. So "4000:3000" would run it on port 4000.
      - "3000:3000"
    depends_on:
      - database
    command: "run-app"