default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= "database" if ENV["POSTGRES_PASSWORD"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: faker_word_maker_development

test:
  <<: *default
  database: faker_word_maker_test

production:
  <<: *default
  database: faker_word_maker_production
